//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luis.MasteringExtJs.WebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menu1 = new HashSet<Menu>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string Iconcls { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> MenuId { get; set; }
    
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
