//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luis.MasteringExtJs.WebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
